//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _202303240733019_Initial_Database {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _202303240733019_Initial_Database() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLayer.Migrations.202303240733019_Initial_Database", typeof(_202303240733019_Initial_Database).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEANVb227bRhB9L9B/IPjUFo4p2wjQGlICR7ILofEFlp32LViRI3nR5ZLlLl0JRb+sD/2k/kKHV/GyJJeSJScIEEi7O2cuOzMczsj//fPv8P3KZcYzBIJ6fGSeHA9MA7jtOZQvR2YoF29+NN+/+/ab4aXjroxP2bmz6BxScjEyn6T0zy1L2E/gEnHsUjvwhLeQx7bnWsTxrNPB4Cfr5MQChDARyzCG9yGX1IX4C34de9wGX4aEXXsOMJGu484sRjVuiAvCJzaMzAmR5CNZQ2AaF4wSFGAGbGEahHNPEoninT8KmMnA48uZjwuEPax9wHMLwgSkYp9vjutqMDiNNLA2hBmUHQrpuT0BT85Sk1hV8q0Ma+YmQ6NdonHlOtI6NtzIvCNLGHuuC1yaRpXf+ZgF0dmCaY8LBEdGvnyUOwD6SfTvyBiHTIYBjDiEMiDsyLgL54zav8D6wfsd+IiHjBVlQ+lwr7SAS3eB50Mg1/ewSCVOmU8npmGV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
